# n8n Deployment Fix
# Apply with: kubectl apply -f n8n-deployment-fix.yaml

apiVersion: apps/v1
kind: Deployment
metadata:
  name: n8n
  namespace: n8n-prod
  labels:
    app: n8n
    environment: production
spec:
  replicas: 1
  selector:
    matchLabels:
      app: n8n
  template:
    metadata:
      labels:
        app: n8n
        environment: production
    spec:
      serviceAccountName: n8n
      securityContext:
        fsGroup: 1000
        runAsNonRoot: true
        runAsUser: 1000
      nodeSelector:
        kubernetes.io/os: linux
      containers:
      - name: n8n
        image: n8nio/n8n:1.115.2
        ports:
        - containerPort: 5678
          name: http
        env:
        - name: N8N_HOST
          value: "n8n.ii-us.com"
        - name: N8N_PORT
          value: "5678"
        - name: N8N_PROTOCOL
          value: "https"
        - name: WEBHOOK_URL
          value: "https://n8n.ii-us.com"
        - name: GENERIC_TIMEZONE
          value: "America/New_York"
        - name: N8N_LOG_LEVEL
          value: "info"
        - name: N8N_USER_MANAGEMENT_DISABLED
          value: "false"
        - name: N8N_SECURE_COOKIE
          value: "true"
        - name: N8N_ENCRYPTION_KEY
          valueFrom:
            secretKeyRef:
              name: n8n-secrets
              key: N8N_ENCRYPTION_KEY
        # NEW: Fix SQLite performance warning
        - name: DB_SQLITE_POOL_SIZE
          value: "3"
        # NEW: Enable task runners (recommended by n8n)
        - name: N8N_RUNNERS_ENABLED
          value: "true"
        # NEW: Block env access in nodes (security best practice)
        - name: N8N_BLOCK_ENV_ACCESS_IN_NODE
          value: "false"
        # NEW: Disable bare repos (security)
        - name: N8N_GIT_NODE_DISABLE_BARE_REPOS
          value: "true"
        # NEW: Enforce settings file permissions
        - name: N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS
          value: "true"

        # FIXED: Increased resource limits
        resources:
          requests:
            cpu: 250m      # Increased from 100m
            memory: 512Mi  # Increased from 256Mi
          limits:
            cpu: 1000m     # Increased from 200m (5x increase!)
            memory: 2Gi    # Increased from 1Gi

        # FIXED: Increased probe timeouts
        livenessProbe:
          httpGet:
            path: /healthz
            port: 5678
          initialDelaySeconds: 60    # Increased from 30
          periodSeconds: 15          # Increased from 10
          timeoutSeconds: 10         # Increased from 5
          failureThreshold: 5        # Increased from 3

        readinessProbe:
          httpGet:
            path: /healthz
            port: 5678
          initialDelaySeconds: 30    # Increased from 10
          periodSeconds: 10          # Increased from 5
          timeoutSeconds: 8          # Increased from 3
          failureThreshold: 5        # Increased from 3

        volumeMounts:
        - name: n8n-data
          mountPath: /home/node/.n8n

      volumes:
      - name: n8n-data
        persistentVolumeClaim:
          claimName: n8n-data
